// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/venue/v1/venue.proto

package venuev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Venue messages
type CreateVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVenueRequest) Reset() {
	*x = CreateVenueRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVenueRequest) ProtoMessage() {}

func (x *CreateVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVenueRequest.ProtoReflect.Descriptor instead.
func (*CreateVenueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVenueRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateVenueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVenueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVenueRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateVenueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateVenueRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateVenueRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreateVenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVenueResponse) Reset() {
	*x = CreateVenueResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVenueResponse) ProtoMessage() {}

func (x *CreateVenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVenueResponse.ProtoReflect.Descriptor instead.
func (*CreateVenueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVenueResponse) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

type GetVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVenueRequest) Reset() {
	*x = GetVenueRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVenueRequest) ProtoMessage() {}

func (x *GetVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVenueRequest.ProtoReflect.Descriptor instead.
func (*GetVenueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{2}
}

func (x *GetVenueRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

type GetVenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVenueResponse) Reset() {
	*x = GetVenueResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVenueResponse) ProtoMessage() {}

func (x *GetVenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVenueResponse.ProtoReflect.Descriptor instead.
func (*GetVenueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{3}
}

func (x *GetVenueResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVenueResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetVenueResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVenueResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetVenueResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetVenueResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetVenueResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetVenueResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetVenueResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetVenueResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListVenuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`                          // Filter by city (optional)
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // Page number (1-based)
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Items per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesRequest) Reset() {
	*x = ListVenuesRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesRequest) ProtoMessage() {}

func (x *ListVenuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesRequest.ProtoReflect.Descriptor instead.
func (*ListVenuesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{4}
}

func (x *ListVenuesRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ListVenuesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVenuesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListVenuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetVenueResponse    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesResponse) Reset() {
	*x = ListVenuesResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesResponse) ProtoMessage() {}

func (x *ListVenuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesResponse.ProtoReflect.Descriptor instead.
func (*ListVenuesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{5}
}

func (x *ListVenuesResponse) GetItems() []*GetVenueResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListVenuesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVenueRequest) Reset() {
	*x = UpdateVenueRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVenueRequest) ProtoMessage() {}

func (x *UpdateVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVenueRequest.ProtoReflect.Descriptor instead.
func (*UpdateVenueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVenueRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *UpdateVenueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVenueRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateVenueRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateVenueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateVenueRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateVenueRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type UpdateVenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVenueResponse) Reset() {
	*x = UpdateVenueResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVenueResponse) ProtoMessage() {}

func (x *UpdateVenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVenueResponse.ProtoReflect.Descriptor instead.
func (*UpdateVenueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateVenueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVenueRequest) Reset() {
	*x = DeleteVenueRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVenueRequest) ProtoMessage() {}

func (x *DeleteVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVenueRequest.ProtoReflect.Descriptor instead.
func (*DeleteVenueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVenueRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

type DeleteVenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVenueResponse) Reset() {
	*x = DeleteVenueResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVenueResponse) ProtoMessage() {}

func (x *DeleteVenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVenueResponse.ProtoReflect.Descriptor instead.
func (*DeleteVenueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVenueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Resource messages
type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SportType     string                 `protobuf:"bytes,3,opt,name=sport_type,json=sportType,proto3" json:"sport_type,omitempty"` // tennis, football, basketball, etc.
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SurfaceType   string                 `protobuf:"bytes,5,opt,name=surface_type,json=surfaceType,proto3" json:"surface_type,omitempty"` // grass, clay, hardcourt, etc.
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{10}
}

func (x *CreateResourceRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *CreateResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateResourceRequest) GetSportType() string {
	if x != nil {
		return x.SportType
	}
	return ""
}

func (x *CreateResourceRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateResourceRequest) GetSurfaceType() string {
	if x != nil {
		return x.SurfaceType
	}
	return ""
}

func (x *CreateResourceRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{11}
}

func (x *CreateResourceResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{12}
}

func (x *GetResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VenueId       string                 `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SportType     string                 `protobuf:"bytes,4,opt,name=sport_type,json=sportType,proto3" json:"sport_type,omitempty"`
	Capacity      int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SurfaceType   string                 `protobuf:"bytes,6,opt,name=surface_type,json=surfaceType,proto3" json:"surface_type,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{13}
}

func (x *GetResourceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResourceResponse) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *GetResourceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetResourceResponse) GetSportType() string {
	if x != nil {
		return x.SportType
	}
	return ""
}

func (x *GetResourceResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *GetResourceResponse) GetSurfaceType() string {
	if x != nil {
		return x.SurfaceType
	}
	return ""
}

func (x *GetResourceResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetResourceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetResourceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListResourcesByVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // Filter to only active resources
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesByVenueRequest) Reset() {
	*x = ListResourcesByVenueRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesByVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesByVenueRequest) ProtoMessage() {}

func (x *ListResourcesByVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesByVenueRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesByVenueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{14}
}

func (x *ListResourcesByVenueRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *ListResourcesByVenueRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListResourcesByVenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetResourceResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesByVenueResponse) Reset() {
	*x = ListResourcesByVenueResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesByVenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesByVenueResponse) ProtoMessage() {}

func (x *ListResourcesByVenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesByVenueResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesByVenueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{15}
}

func (x *ListResourcesByVenueResponse) GetItems() []*GetResourceResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SportType     string                 `protobuf:"bytes,3,opt,name=sport_type,json=sportType,proto3" json:"sport_type,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SurfaceType   string                 `protobuf:"bytes,5,opt,name=surface_type,json=surfaceType,proto3" json:"surface_type,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpdateResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResourceRequest) GetSportType() string {
	if x != nil {
		return x.SportType
	}
	return ""
}

func (x *UpdateResourceRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UpdateResourceRequest) GetSurfaceType() string {
	if x != nil {
		return x.SurfaceType
	}
	return ""
}

func (x *UpdateResourceRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceResponse) Reset() {
	*x = UpdateResourceResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceResponse) ProtoMessage() {}

func (x *UpdateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteResourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Schedule messages
type ScheduleSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayOfWeek     int32                  `protobuf:"varint,1,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"` // 0=Sunday, 6=Saturday
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // HH:MM format
	EndTime       string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`          // HH:MM format
	BasePrice     float64                `protobuf:"fixed64,4,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleSlot) Reset() {
	*x = ScheduleSlot{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSlot) ProtoMessage() {}

func (x *ScheduleSlot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSlot.ProtoReflect.Descriptor instead.
func (*ScheduleSlot) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{20}
}

func (x *ScheduleSlot) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *ScheduleSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ScheduleSlot) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

type SetResourceScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Slots         []*ScheduleSlot        `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResourceScheduleRequest) Reset() {
	*x = SetResourceScheduleRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResourceScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResourceScheduleRequest) ProtoMessage() {}

func (x *SetResourceScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResourceScheduleRequest.ProtoReflect.Descriptor instead.
func (*SetResourceScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{21}
}

func (x *SetResourceScheduleRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SetResourceScheduleRequest) GetSlots() []*ScheduleSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type SetResourceScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResourceScheduleResponse) Reset() {
	*x = SetResourceScheduleResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResourceScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResourceScheduleResponse) ProtoMessage() {}

func (x *SetResourceScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResourceScheduleResponse.ProtoReflect.Descriptor instead.
func (*SetResourceScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{22}
}

func (x *SetResourceScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetResourceScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceScheduleRequest) Reset() {
	*x = GetResourceScheduleRequest{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceScheduleRequest) ProtoMessage() {}

func (x *GetResourceScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetResourceScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{23}
}

func (x *GetResourceScheduleRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetResourceScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*ScheduleSlot        `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceScheduleResponse) Reset() {
	*x = GetResourceScheduleResponse{}
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceScheduleResponse) ProtoMessage() {}

func (x *GetResourceScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_venue_v1_venue_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetResourceScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_venue_v1_venue_proto_rawDescGZIP(), []int{24}
}

func (x *GetResourceScheduleResponse) GetSlots() []*ScheduleSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_api_proto_venue_v1_venue_proto protoreflect.FileDescriptor

const file_api_proto_venue_v1_venue_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/venue/v1/venue.proto\x12\bvenue.v1\"\xcd\x01\n" +
	"\x12CreateVenueRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\"0\n" +
	"\x13CreateVenueResponse\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\",\n" +
	"\x0fGetVenueRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\"\x99\x02\n" +
	"\x10GetVenueResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"X\n" +
	"\x11ListVenuesRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"g\n" +
	"\x12ListVenuesResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.venue.v1.GetVenueResponseR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xcd\x01\n" +
	"\x12UpdateVenueRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\"/\n" +
	"\x13UpdateVenueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x12DeleteVenueRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\"/\n" +
	"\x13DeleteVenueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc1\x01\n" +
	"\x15CreateResourceRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sport_type\x18\x03 \x01(\tR\tsportType\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12!\n" +
	"\fsurface_type\x18\x05 \x01(\tR\vsurfaceType\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"9\n" +
	"\x16CreateResourceResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"5\n" +
	"\x12GetResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"\x8d\x02\n" +
	"\x13GetResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvenue_id\x18\x02 \x01(\tR\avenueId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sport_type\x18\x04 \x01(\tR\tsportType\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12!\n" +
	"\fsurface_type\x18\x06 \x01(\tR\vsurfaceType\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"Y\n" +
	"\x1bListResourcesByVenueRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"S\n" +
	"\x1cListResourcesByVenueResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.venue.v1.GetResourceResponseR\x05items\"\xc7\x01\n" +
	"\x15UpdateResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sport_type\x18\x03 \x01(\tR\tsportType\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12!\n" +
	"\fsurface_type\x18\x05 \x01(\tR\vsurfaceType\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"2\n" +
	"\x16UpdateResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x15DeleteResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"2\n" +
	"\x16DeleteResourceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x01\n" +
	"\fScheduleSlot\x12\x1e\n" +
	"\vday_of_week\x18\x01 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12\x1d\n" +
	"\n" +
	"base_price\x18\x04 \x01(\x01R\tbasePrice\"k\n" +
	"\x1aSetResourceScheduleRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12,\n" +
	"\x05slots\x18\x02 \x03(\v2\x16.venue.v1.ScheduleSlotR\x05slots\"7\n" +
	"\x1bSetResourceScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\x1aGetResourceScheduleRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"K\n" +
	"\x1bGetResourceScheduleResponse\x12,\n" +
	"\x05slots\x18\x01 \x03(\v2\x16.venue.v1.ScheduleSlotR\x05slots2\xf8\a\n" +
	"\fVenueService\x12J\n" +
	"\vCreateVenue\x12\x1c.venue.v1.CreateVenueRequest\x1a\x1d.venue.v1.CreateVenueResponse\x12A\n" +
	"\bGetVenue\x12\x19.venue.v1.GetVenueRequest\x1a\x1a.venue.v1.GetVenueResponse\x12G\n" +
	"\n" +
	"ListVenues\x12\x1b.venue.v1.ListVenuesRequest\x1a\x1c.venue.v1.ListVenuesResponse\x12J\n" +
	"\vUpdateVenue\x12\x1c.venue.v1.UpdateVenueRequest\x1a\x1d.venue.v1.UpdateVenueResponse\x12J\n" +
	"\vDeleteVenue\x12\x1c.venue.v1.DeleteVenueRequest\x1a\x1d.venue.v1.DeleteVenueResponse\x12S\n" +
	"\x0eCreateResource\x12\x1f.venue.v1.CreateResourceRequest\x1a .venue.v1.CreateResourceResponse\x12J\n" +
	"\vGetResource\x12\x1c.venue.v1.GetResourceRequest\x1a\x1d.venue.v1.GetResourceResponse\x12e\n" +
	"\x14ListResourcesByVenue\x12%.venue.v1.ListResourcesByVenueRequest\x1a&.venue.v1.ListResourcesByVenueResponse\x12S\n" +
	"\x0eUpdateResource\x12\x1f.venue.v1.UpdateResourceRequest\x1a .venue.v1.UpdateResourceResponse\x12S\n" +
	"\x0eDeleteResource\x12\x1f.venue.v1.DeleteResourceRequest\x1a .venue.v1.DeleteResourceResponse\x12b\n" +
	"\x13SetResourceSchedule\x12$.venue.v1.SetResourceScheduleRequest\x1a%.venue.v1.SetResourceScheduleResponse\x12b\n" +
	"\x13GetResourceSchedule\x12$.venue.v1.GetResourceScheduleRequest\x1a%.venue.v1.GetResourceScheduleResponseB;Z9github.com/diploma/api-gateway/api/proto/venue/v1;venuev1b\x06proto3"

var (
	file_api_proto_venue_v1_venue_proto_rawDescOnce sync.Once
	file_api_proto_venue_v1_venue_proto_rawDescData []byte
)

func file_api_proto_venue_v1_venue_proto_rawDescGZIP() []byte {
	file_api_proto_venue_v1_venue_proto_rawDescOnce.Do(func() {
		file_api_proto_venue_v1_venue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_venue_v1_venue_proto_rawDesc), len(file_api_proto_venue_v1_venue_proto_rawDesc)))
	})
	return file_api_proto_venue_v1_venue_proto_rawDescData
}

var file_api_proto_venue_v1_venue_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_venue_v1_venue_proto_goTypes = []any{
	(*CreateVenueRequest)(nil),           // 0: venue.v1.CreateVenueRequest
	(*CreateVenueResponse)(nil),          // 1: venue.v1.CreateVenueResponse
	(*GetVenueRequest)(nil),              // 2: venue.v1.GetVenueRequest
	(*GetVenueResponse)(nil),             // 3: venue.v1.GetVenueResponse
	(*ListVenuesRequest)(nil),            // 4: venue.v1.ListVenuesRequest
	(*ListVenuesResponse)(nil),           // 5: venue.v1.ListVenuesResponse
	(*UpdateVenueRequest)(nil),           // 6: venue.v1.UpdateVenueRequest
	(*UpdateVenueResponse)(nil),          // 7: venue.v1.UpdateVenueResponse
	(*DeleteVenueRequest)(nil),           // 8: venue.v1.DeleteVenueRequest
	(*DeleteVenueResponse)(nil),          // 9: venue.v1.DeleteVenueResponse
	(*CreateResourceRequest)(nil),        // 10: venue.v1.CreateResourceRequest
	(*CreateResourceResponse)(nil),       // 11: venue.v1.CreateResourceResponse
	(*GetResourceRequest)(nil),           // 12: venue.v1.GetResourceRequest
	(*GetResourceResponse)(nil),          // 13: venue.v1.GetResourceResponse
	(*ListResourcesByVenueRequest)(nil),  // 14: venue.v1.ListResourcesByVenueRequest
	(*ListResourcesByVenueResponse)(nil), // 15: venue.v1.ListResourcesByVenueResponse
	(*UpdateResourceRequest)(nil),        // 16: venue.v1.UpdateResourceRequest
	(*UpdateResourceResponse)(nil),       // 17: venue.v1.UpdateResourceResponse
	(*DeleteResourceRequest)(nil),        // 18: venue.v1.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),       // 19: venue.v1.DeleteResourceResponse
	(*ScheduleSlot)(nil),                 // 20: venue.v1.ScheduleSlot
	(*SetResourceScheduleRequest)(nil),   // 21: venue.v1.SetResourceScheduleRequest
	(*SetResourceScheduleResponse)(nil),  // 22: venue.v1.SetResourceScheduleResponse
	(*GetResourceScheduleRequest)(nil),   // 23: venue.v1.GetResourceScheduleRequest
	(*GetResourceScheduleResponse)(nil),  // 24: venue.v1.GetResourceScheduleResponse
}
var file_api_proto_venue_v1_venue_proto_depIdxs = []int32{
	3,  // 0: venue.v1.ListVenuesResponse.items:type_name -> venue.v1.GetVenueResponse
	13, // 1: venue.v1.ListResourcesByVenueResponse.items:type_name -> venue.v1.GetResourceResponse
	20, // 2: venue.v1.SetResourceScheduleRequest.slots:type_name -> venue.v1.ScheduleSlot
	20, // 3: venue.v1.GetResourceScheduleResponse.slots:type_name -> venue.v1.ScheduleSlot
	0,  // 4: venue.v1.VenueService.CreateVenue:input_type -> venue.v1.CreateVenueRequest
	2,  // 5: venue.v1.VenueService.GetVenue:input_type -> venue.v1.GetVenueRequest
	4,  // 6: venue.v1.VenueService.ListVenues:input_type -> venue.v1.ListVenuesRequest
	6,  // 7: venue.v1.VenueService.UpdateVenue:input_type -> venue.v1.UpdateVenueRequest
	8,  // 8: venue.v1.VenueService.DeleteVenue:input_type -> venue.v1.DeleteVenueRequest
	10, // 9: venue.v1.VenueService.CreateResource:input_type -> venue.v1.CreateResourceRequest
	12, // 10: venue.v1.VenueService.GetResource:input_type -> venue.v1.GetResourceRequest
	14, // 11: venue.v1.VenueService.ListResourcesByVenue:input_type -> venue.v1.ListResourcesByVenueRequest
	16, // 12: venue.v1.VenueService.UpdateResource:input_type -> venue.v1.UpdateResourceRequest
	18, // 13: venue.v1.VenueService.DeleteResource:input_type -> venue.v1.DeleteResourceRequest
	21, // 14: venue.v1.VenueService.SetResourceSchedule:input_type -> venue.v1.SetResourceScheduleRequest
	23, // 15: venue.v1.VenueService.GetResourceSchedule:input_type -> venue.v1.GetResourceScheduleRequest
	1,  // 16: venue.v1.VenueService.CreateVenue:output_type -> venue.v1.CreateVenueResponse
	3,  // 17: venue.v1.VenueService.GetVenue:output_type -> venue.v1.GetVenueResponse
	5,  // 18: venue.v1.VenueService.ListVenues:output_type -> venue.v1.ListVenuesResponse
	7,  // 19: venue.v1.VenueService.UpdateVenue:output_type -> venue.v1.UpdateVenueResponse
	9,  // 20: venue.v1.VenueService.DeleteVenue:output_type -> venue.v1.DeleteVenueResponse
	11, // 21: venue.v1.VenueService.CreateResource:output_type -> venue.v1.CreateResourceResponse
	13, // 22: venue.v1.VenueService.GetResource:output_type -> venue.v1.GetResourceResponse
	15, // 23: venue.v1.VenueService.ListResourcesByVenue:output_type -> venue.v1.ListResourcesByVenueResponse
	17, // 24: venue.v1.VenueService.UpdateResource:output_type -> venue.v1.UpdateResourceResponse
	19, // 25: venue.v1.VenueService.DeleteResource:output_type -> venue.v1.DeleteResourceResponse
	22, // 26: venue.v1.VenueService.SetResourceSchedule:output_type -> venue.v1.SetResourceScheduleResponse
	24, // 27: venue.v1.VenueService.GetResourceSchedule:output_type -> venue.v1.GetResourceScheduleResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_venue_v1_venue_proto_init() }
func file_api_proto_venue_v1_venue_proto_init() {
	if File_api_proto_venue_v1_venue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_venue_v1_venue_proto_rawDesc), len(file_api_proto_venue_v1_venue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_venue_v1_venue_proto_goTypes,
		DependencyIndexes: file_api_proto_venue_v1_venue_proto_depIdxs,
		MessageInfos:      file_api_proto_venue_v1_venue_proto_msgTypes,
	}.Build()
	File_api_proto_venue_v1_venue_proto = out.File
	file_api_proto_venue_v1_venue_proto_goTypes = nil
	file_api_proto_venue_v1_venue_proto_depIdxs = nil
}
