// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/v1/venue.proto

package venuev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VenueService_CreateVenue_FullMethodName          = "/venue.v1.VenueService/CreateVenue"
	VenueService_GetVenue_FullMethodName             = "/venue.v1.VenueService/GetVenue"
	VenueService_ListVenues_FullMethodName           = "/venue.v1.VenueService/ListVenues"
	VenueService_UpdateVenue_FullMethodName          = "/venue.v1.VenueService/UpdateVenue"
	VenueService_DeleteVenue_FullMethodName          = "/venue.v1.VenueService/DeleteVenue"
	VenueService_CreateResource_FullMethodName       = "/venue.v1.VenueService/CreateResource"
	VenueService_GetResource_FullMethodName          = "/venue.v1.VenueService/GetResource"
	VenueService_ListResourcesByVenue_FullMethodName = "/venue.v1.VenueService/ListResourcesByVenue"
	VenueService_UpdateResource_FullMethodName       = "/venue.v1.VenueService/UpdateResource"
	VenueService_DeleteResource_FullMethodName       = "/venue.v1.VenueService/DeleteResource"
	VenueService_SetResourceSchedule_FullMethodName  = "/venue.v1.VenueService/SetResourceSchedule"
	VenueService_GetResourceSchedule_FullMethodName  = "/venue.v1.VenueService/GetResourceSchedule"
)

// VenueServiceClient is the client API for VenueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VenueService manages venues and resources
type VenueServiceClient interface {
	// Venue management
	CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*CreateVenueResponse, error)
	GetVenue(ctx context.Context, in *GetVenueRequest, opts ...grpc.CallOption) (*GetVenueResponse, error)
	ListVenues(ctx context.Context, in *ListVenuesRequest, opts ...grpc.CallOption) (*ListVenuesResponse, error)
	UpdateVenue(ctx context.Context, in *UpdateVenueRequest, opts ...grpc.CallOption) (*UpdateVenueResponse, error)
	DeleteVenue(ctx context.Context, in *DeleteVenueRequest, opts ...grpc.CallOption) (*DeleteVenueResponse, error)
	// Resource management
	CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error)
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error)
	ListResourcesByVenue(ctx context.Context, in *ListResourcesByVenueRequest, opts ...grpc.CallOption) (*ListResourcesByVenueResponse, error)
	UpdateResource(ctx context.Context, in *UpdateResourceRequest, opts ...grpc.CallOption) (*UpdateResourceResponse, error)
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	// Schedule management
	SetResourceSchedule(ctx context.Context, in *SetResourceScheduleRequest, opts ...grpc.CallOption) (*SetResourceScheduleResponse, error)
	GetResourceSchedule(ctx context.Context, in *GetResourceScheduleRequest, opts ...grpc.CallOption) (*GetResourceScheduleResponse, error)
}

type venueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVenueServiceClient(cc grpc.ClientConnInterface) VenueServiceClient {
	return &venueServiceClient{cc}
}

func (c *venueServiceClient) CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*CreateVenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVenueResponse)
	err := c.cc.Invoke(ctx, VenueService_CreateVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetVenue(ctx context.Context, in *GetVenueRequest, opts ...grpc.CallOption) (*GetVenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVenueResponse)
	err := c.cc.Invoke(ctx, VenueService_GetVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) ListVenues(ctx context.Context, in *ListVenuesRequest, opts ...grpc.CallOption) (*ListVenuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVenuesResponse)
	err := c.cc.Invoke(ctx, VenueService_ListVenues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) UpdateVenue(ctx context.Context, in *UpdateVenueRequest, opts ...grpc.CallOption) (*UpdateVenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVenueResponse)
	err := c.cc.Invoke(ctx, VenueService_UpdateVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) DeleteVenue(ctx context.Context, in *DeleteVenueRequest, opts ...grpc.CallOption) (*DeleteVenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVenueResponse)
	err := c.cc.Invoke(ctx, VenueService_DeleteVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResourceResponse)
	err := c.cc.Invoke(ctx, VenueService_CreateResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceResponse)
	err := c.cc.Invoke(ctx, VenueService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) ListResourcesByVenue(ctx context.Context, in *ListResourcesByVenueRequest, opts ...grpc.CallOption) (*ListResourcesByVenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesByVenueResponse)
	err := c.cc.Invoke(ctx, VenueService_ListResourcesByVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) UpdateResource(ctx context.Context, in *UpdateResourceRequest, opts ...grpc.CallOption) (*UpdateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResourceResponse)
	err := c.cc.Invoke(ctx, VenueService_UpdateResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, VenueService_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) SetResourceSchedule(ctx context.Context, in *SetResourceScheduleRequest, opts ...grpc.CallOption) (*SetResourceScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResourceScheduleResponse)
	err := c.cc.Invoke(ctx, VenueService_SetResourceSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetResourceSchedule(ctx context.Context, in *GetResourceScheduleRequest, opts ...grpc.CallOption) (*GetResourceScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceScheduleResponse)
	err := c.cc.Invoke(ctx, VenueService_GetResourceSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VenueServiceServer is the server API for VenueService service.
// All implementations must embed UnimplementedVenueServiceServer
// for forward compatibility.
//
// VenueService manages venues and resources
type VenueServiceServer interface {
	// Venue management
	CreateVenue(context.Context, *CreateVenueRequest) (*CreateVenueResponse, error)
	GetVenue(context.Context, *GetVenueRequest) (*GetVenueResponse, error)
	ListVenues(context.Context, *ListVenuesRequest) (*ListVenuesResponse, error)
	UpdateVenue(context.Context, *UpdateVenueRequest) (*UpdateVenueResponse, error)
	DeleteVenue(context.Context, *DeleteVenueRequest) (*DeleteVenueResponse, error)
	// Resource management
	CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error)
	GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error)
	ListResourcesByVenue(context.Context, *ListResourcesByVenueRequest) (*ListResourcesByVenueResponse, error)
	UpdateResource(context.Context, *UpdateResourceRequest) (*UpdateResourceResponse, error)
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	// Schedule management
	SetResourceSchedule(context.Context, *SetResourceScheduleRequest) (*SetResourceScheduleResponse, error)
	GetResourceSchedule(context.Context, *GetResourceScheduleRequest) (*GetResourceScheduleResponse, error)
	mustEmbedUnimplementedVenueServiceServer()
}

// UnimplementedVenueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVenueServiceServer struct{}

func (UnimplementedVenueServiceServer) CreateVenue(context.Context, *CreateVenueRequest) (*CreateVenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVenue not implemented")
}
func (UnimplementedVenueServiceServer) GetVenue(context.Context, *GetVenueRequest) (*GetVenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVenue not implemented")
}
func (UnimplementedVenueServiceServer) ListVenues(context.Context, *ListVenuesRequest) (*ListVenuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVenues not implemented")
}
func (UnimplementedVenueServiceServer) UpdateVenue(context.Context, *UpdateVenueRequest) (*UpdateVenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVenue not implemented")
}
func (UnimplementedVenueServiceServer) DeleteVenue(context.Context, *DeleteVenueRequest) (*DeleteVenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVenue not implemented")
}
func (UnimplementedVenueServiceServer) CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateResource not implemented")
}
func (UnimplementedVenueServiceServer) GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedVenueServiceServer) ListResourcesByVenue(context.Context, *ListResourcesByVenueRequest) (*ListResourcesByVenueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResourcesByVenue not implemented")
}
func (UnimplementedVenueServiceServer) UpdateResource(context.Context, *UpdateResourceRequest) (*UpdateResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateResource not implemented")
}
func (UnimplementedVenueServiceServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedVenueServiceServer) SetResourceSchedule(context.Context, *SetResourceScheduleRequest) (*SetResourceScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetResourceSchedule not implemented")
}
func (UnimplementedVenueServiceServer) GetResourceSchedule(context.Context, *GetResourceScheduleRequest) (*GetResourceScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResourceSchedule not implemented")
}
func (UnimplementedVenueServiceServer) mustEmbedUnimplementedVenueServiceServer() {}
func (UnimplementedVenueServiceServer) testEmbeddedByValue()                      {}

// UnsafeVenueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VenueServiceServer will
// result in compilation errors.
type UnsafeVenueServiceServer interface {
	mustEmbedUnimplementedVenueServiceServer()
}

func RegisterVenueServiceServer(s grpc.ServiceRegistrar, srv VenueServiceServer) {
	// If the following call panics, it indicates UnimplementedVenueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VenueService_ServiceDesc, srv)
}

func _VenueService_CreateVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).CreateVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_CreateVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).CreateVenue(ctx, req.(*CreateVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetVenue(ctx, req.(*GetVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_ListVenues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVenuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).ListVenues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_ListVenues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).ListVenues(ctx, req.(*ListVenuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_UpdateVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).UpdateVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_UpdateVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).UpdateVenue(ctx, req.(*UpdateVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_DeleteVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).DeleteVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_DeleteVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).DeleteVenue(ctx, req.(*DeleteVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_CreateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).CreateResource(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_ListResourcesByVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesByVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).ListResourcesByVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_ListResourcesByVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).ListResourcesByVenue(ctx, req.(*ListResourcesByVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_UpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).UpdateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_UpdateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).UpdateResource(ctx, req.(*UpdateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_SetResourceSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetResourceScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).SetResourceSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_SetResourceSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).SetResourceSchedule(ctx, req.(*SetResourceScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetResourceSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetResourceSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetResourceSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetResourceSchedule(ctx, req.(*GetResourceScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VenueService_ServiceDesc is the grpc.ServiceDesc for VenueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VenueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "venue.v1.VenueService",
	HandlerType: (*VenueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVenue",
			Handler:    _VenueService_CreateVenue_Handler,
		},
		{
			MethodName: "GetVenue",
			Handler:    _VenueService_GetVenue_Handler,
		},
		{
			MethodName: "ListVenues",
			Handler:    _VenueService_ListVenues_Handler,
		},
		{
			MethodName: "UpdateVenue",
			Handler:    _VenueService_UpdateVenue_Handler,
		},
		{
			MethodName: "DeleteVenue",
			Handler:    _VenueService_DeleteVenue_Handler,
		},
		{
			MethodName: "CreateResource",
			Handler:    _VenueService_CreateResource_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _VenueService_GetResource_Handler,
		},
		{
			MethodName: "ListResourcesByVenue",
			Handler:    _VenueService_ListResourcesByVenue_Handler,
		},
		{
			MethodName: "UpdateResource",
			Handler:    _VenueService_UpdateResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _VenueService_DeleteResource_Handler,
		},
		{
			MethodName: "SetResourceSchedule",
			Handler:    _VenueService_SetResourceSchedule_Handler,
		},
		{
			MethodName: "GetResourceSchedule",
			Handler:    _VenueService_GetResourceSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/venue.proto",
}
