// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/v1/reservation.proto

package reservationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApartmentId   string                 `protobuf:"bytes,2,opt,name=apartment_id,json=apartmentId,proto3" json:"apartment_id,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_api_v1_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReservationRequest) GetApartmentId() string {
	if x != nil {
		return x.ApartmentId
	}
	return ""
}

func (x *CreateReservationRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_api_v1_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_api_v1_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ConfirmReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationResponse) Reset() {
	*x = ConfirmReservationResponse{}
	mi := &file_api_v1_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationResponse) ProtoMessage() {}

func (x *ConfirmReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_api_v1_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_api_v1_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *CancelReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_api_v1_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *GetReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type GetReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApartmentId   string                 `protobuf:"bytes,3,opt,name=apartment_id,json=apartmentId,proto3" json:"apartment_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ReservedAt    string                 `protobuf:"bytes,5,opt,name=reserved_at,json=reservedAt,proto3" json:"reserved_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationResponse) Reset() {
	*x = GetReservationResponse{}
	mi := &file_api_v1_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationResponse) ProtoMessage() {}

func (x *GetReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationResponse.ProtoReflect.Descriptor instead.
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *GetReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReservationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReservationResponse) GetApartmentId() string {
	if x != nil {
		return x.ApartmentId
	}
	return ""
}

func (x *GetReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetReservationResponse) GetReservedAt() string {
	if x != nil {
		return x.ReservedAt
	}
	return ""
}

func (x *GetReservationResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *GetReservationResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ListReservationsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsByUserRequest) Reset() {
	*x = ListReservationsByUserRequest{}
	mi := &file_api_v1_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsByUserRequest) ProtoMessage() {}

func (x *ListReservationsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsByUserRequest.ProtoReflect.Descriptor instead.
func (*ListReservationsByUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *ListReservationsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListReservationsByUserResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*GetReservationResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationsByUserResponse) Reset() {
	*x = ListReservationsByUserResponse{}
	mi := &file_api_v1_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationsByUserResponse) ProtoMessage() {}

func (x *ListReservationsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationsByUserResponse.ProtoReflect.Descriptor instead.
func (*ListReservationsByUserResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *ListReservationsByUserResponse) GetItems() []*GetReservationResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_v1_reservation_proto protoreflect.FileDescriptor

const file_api_v1_reservation_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1/reservation.proto\x12\x0ereservation.v1\"p\n" +
	"\x18CreateReservationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fapartment_id\x18\x02 \x01(\tR\vapartmentId\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"B\n" +
	"\x19CreateReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"B\n" +
	"\x19ConfirmReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"6\n" +
	"\x1aConfirmReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"5\n" +
	"\x19CancelReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\x15GetReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\xd6\x01\n" +
	"\x16GetReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fapartment_id\x18\x03 \x01(\tR\vapartmentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vreserved_at\x18\x05 \x01(\tR\n" +
	"reservedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\"8\n" +
	"\x1dListReservationsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x1eListReservationsByUserResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.reservation.v1.GetReservationResponseR\x05items2\xaf\x04\n" +
	"\x12ReservationService\x12h\n" +
	"\x11CreateReservation\x12(.reservation.v1.CreateReservationRequest\x1a).reservation.v1.CreateReservationResponse\x12k\n" +
	"\x12ConfirmReservation\x12).reservation.v1.ConfirmReservationRequest\x1a*.reservation.v1.ConfirmReservationResponse\x12h\n" +
	"\x11CancelReservation\x12(.reservation.v1.CancelReservationRequest\x1a).reservation.v1.CancelReservationResponse\x12_\n" +
	"\x0eGetReservation\x12%.reservation.v1.GetReservationRequest\x1a&.reservation.v1.GetReservationResponse\x12w\n" +
	"\x16ListReservationsByUser\x12-.reservation.v1.ListReservationsByUserRequest\x1a..reservation.v1.ListReservationsByUserResponseB9Z7github.com/diploma/reservation-svc/api/v1;reservationv1b\x06proto3"

var (
	file_api_v1_reservation_proto_rawDescOnce sync.Once
	file_api_v1_reservation_proto_rawDescData []byte
)

func file_api_v1_reservation_proto_rawDescGZIP() []byte {
	file_api_v1_reservation_proto_rawDescOnce.Do(func() {
		file_api_v1_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_reservation_proto_rawDesc), len(file_api_v1_reservation_proto_rawDesc)))
	})
	return file_api_v1_reservation_proto_rawDescData
}

var file_api_v1_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_reservation_proto_goTypes = []any{
	(*CreateReservationRequest)(nil),       // 0: reservation.v1.CreateReservationRequest
	(*CreateReservationResponse)(nil),      // 1: reservation.v1.CreateReservationResponse
	(*ConfirmReservationRequest)(nil),      // 2: reservation.v1.ConfirmReservationRequest
	(*ConfirmReservationResponse)(nil),     // 3: reservation.v1.ConfirmReservationResponse
	(*CancelReservationRequest)(nil),       // 4: reservation.v1.CancelReservationRequest
	(*CancelReservationResponse)(nil),      // 5: reservation.v1.CancelReservationResponse
	(*GetReservationRequest)(nil),          // 6: reservation.v1.GetReservationRequest
	(*GetReservationResponse)(nil),         // 7: reservation.v1.GetReservationResponse
	(*ListReservationsByUserRequest)(nil),  // 8: reservation.v1.ListReservationsByUserRequest
	(*ListReservationsByUserResponse)(nil), // 9: reservation.v1.ListReservationsByUserResponse
}
var file_api_v1_reservation_proto_depIdxs = []int32{
	7, // 0: reservation.v1.ListReservationsByUserResponse.items:type_name -> reservation.v1.GetReservationResponse
	0, // 1: reservation.v1.ReservationService.CreateReservation:input_type -> reservation.v1.CreateReservationRequest
	2, // 2: reservation.v1.ReservationService.ConfirmReservation:input_type -> reservation.v1.ConfirmReservationRequest
	4, // 3: reservation.v1.ReservationService.CancelReservation:input_type -> reservation.v1.CancelReservationRequest
	6, // 4: reservation.v1.ReservationService.GetReservation:input_type -> reservation.v1.GetReservationRequest
	8, // 5: reservation.v1.ReservationService.ListReservationsByUser:input_type -> reservation.v1.ListReservationsByUserRequest
	1, // 6: reservation.v1.ReservationService.CreateReservation:output_type -> reservation.v1.CreateReservationResponse
	3, // 7: reservation.v1.ReservationService.ConfirmReservation:output_type -> reservation.v1.ConfirmReservationResponse
	5, // 8: reservation.v1.ReservationService.CancelReservation:output_type -> reservation.v1.CancelReservationResponse
	7, // 9: reservation.v1.ReservationService.GetReservation:output_type -> reservation.v1.GetReservationResponse
	9, // 10: reservation.v1.ReservationService.ListReservationsByUser:output_type -> reservation.v1.ListReservationsByUserResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_reservation_proto_init() }
func file_api_v1_reservation_proto_init() {
	if File_api_v1_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_reservation_proto_rawDesc), len(file_api_v1_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_reservation_proto_goTypes,
		DependencyIndexes: file_api_v1_reservation_proto_depIdxs,
		MessageInfos:      file_api_v1_reservation_proto_msgTypes,
	}.Build()
	File_api_v1_reservation_proto = out.File
	file_api_v1_reservation_proto_goTypes = nil
	file_api_v1_reservation_proto_depIdxs = nil
}
