// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/session.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session status enum
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_OPEN        SessionStatus = 1 // Accepting participants
	SessionStatus_SESSION_STATUS_FULL        SessionStatus = 2 // Max capacity reached
	SessionStatus_SESSION_STATUS_IN_PROGRESS SessionStatus = 3 // Game started
	SessionStatus_SESSION_STATUS_COMPLETED   SessionStatus = 4 // Game finished
	SessionStatus_SESSION_STATUS_CANCELLED   SessionStatus = 5 // Cancelled by host
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_OPEN",
		2: "SESSION_STATUS_FULL",
		3: "SESSION_STATUS_IN_PROGRESS",
		4: "SESSION_STATUS_COMPLETED",
		5: "SESSION_STATUS_CANCELLED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_OPEN":        1,
		"SESSION_STATUS_FULL":        2,
		"SESSION_STATUS_IN_PROGRESS": 3,
		"SESSION_STATUS_COMPLETED":   4,
		"SESSION_STATUS_CANCELLED":   5,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_session_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_api_v1_session_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{0}
}

// Session visibility enum
type SessionVisibility int32

const (
	SessionVisibility_SESSION_VISIBILITY_UNSPECIFIED SessionVisibility = 0
	SessionVisibility_SESSION_VISIBILITY_PUBLIC      SessionVisibility = 1 // Anyone can see and join
	SessionVisibility_SESSION_VISIBILITY_PRIVATE     SessionVisibility = 2 // Invite-only
)

// Enum value maps for SessionVisibility.
var (
	SessionVisibility_name = map[int32]string{
		0: "SESSION_VISIBILITY_UNSPECIFIED",
		1: "SESSION_VISIBILITY_PUBLIC",
		2: "SESSION_VISIBILITY_PRIVATE",
	}
	SessionVisibility_value = map[string]int32{
		"SESSION_VISIBILITY_UNSPECIFIED": 0,
		"SESSION_VISIBILITY_PUBLIC":      1,
		"SESSION_VISIBILITY_PRIVATE":     2,
	}
)

func (x SessionVisibility) Enum() *SessionVisibility {
	p := new(SessionVisibility)
	*p = x
	return p
}

func (x SessionVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_session_proto_enumTypes[1].Descriptor()
}

func (SessionVisibility) Type() protoreflect.EnumType {
	return &file_api_v1_session_proto_enumTypes[1]
}

func (x SessionVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionVisibility.Descriptor instead.
func (SessionVisibility) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{1}
}

// Participant role enum
type ParticipantRole int32

const (
	ParticipantRole_PARTICIPANT_ROLE_UNSPECIFIED ParticipantRole = 0
	ParticipantRole_PARTICIPANT_ROLE_HOST        ParticipantRole = 1
	ParticipantRole_PARTICIPANT_ROLE_PLAYER      ParticipantRole = 2
)

// Enum value maps for ParticipantRole.
var (
	ParticipantRole_name = map[int32]string{
		0: "PARTICIPANT_ROLE_UNSPECIFIED",
		1: "PARTICIPANT_ROLE_HOST",
		2: "PARTICIPANT_ROLE_PLAYER",
	}
	ParticipantRole_value = map[string]int32{
		"PARTICIPANT_ROLE_UNSPECIFIED": 0,
		"PARTICIPANT_ROLE_HOST":        1,
		"PARTICIPANT_ROLE_PLAYER":      2,
	}
)

func (x ParticipantRole) Enum() *ParticipantRole {
	p := new(ParticipantRole)
	*p = x
	return p
}

func (x ParticipantRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_session_proto_enumTypes[2].Descriptor()
}

func (ParticipantRole) Type() protoreflect.EnumType {
	return &file_api_v1_session_proto_enumTypes[2]
}

func (x ParticipantRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantRole.Descriptor instead.
func (ParticipantRole) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{2}
}

// Participant status enum
type ParticipantStatus int32

const (
	ParticipantStatus_PARTICIPANT_STATUS_UNSPECIFIED ParticipantStatus = 0
	ParticipantStatus_PARTICIPANT_STATUS_JOINED      ParticipantStatus = 1
	ParticipantStatus_PARTICIPANT_STATUS_LEFT        ParticipantStatus = 2
	ParticipantStatus_PARTICIPANT_STATUS_REMOVED     ParticipantStatus = 3
)

// Enum value maps for ParticipantStatus.
var (
	ParticipantStatus_name = map[int32]string{
		0: "PARTICIPANT_STATUS_UNSPECIFIED",
		1: "PARTICIPANT_STATUS_JOINED",
		2: "PARTICIPANT_STATUS_LEFT",
		3: "PARTICIPANT_STATUS_REMOVED",
	}
	ParticipantStatus_value = map[string]int32{
		"PARTICIPANT_STATUS_UNSPECIFIED": 0,
		"PARTICIPANT_STATUS_JOINED":      1,
		"PARTICIPANT_STATUS_LEFT":        2,
		"PARTICIPANT_STATUS_REMOVED":     3,
	}
)

func (x ParticipantStatus) Enum() *ParticipantStatus {
	p := new(ParticipantStatus)
	*p = x
	return p
}

func (x ParticipantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_session_proto_enumTypes[3].Descriptor()
}

func (ParticipantStatus) Type() protoreflect.EnumType {
	return &file_api_v1_session_proto_enumTypes[3]
}

func (x ParticipantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantStatus.Descriptor instead.
func (ParticipantStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{3}
}

// Session messages
type CreateSessionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReservationId       string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	HostId              string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	SportType           string                 `protobuf:"bytes,3,opt,name=sport_type,json=sportType,proto3" json:"sport_type,omitempty"`
	SkillLevel          string                 `protobuf:"bytes,4,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"` // beginner, intermediate, advanced
	MaxParticipants     int32                  `protobuf:"varint,5,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	MinParticipants     int32                  `protobuf:"varint,6,opt,name=min_participants,json=minParticipants,proto3" json:"min_participants,omitempty"`
	PricePerParticipant float64                `protobuf:"fixed64,7,opt,name=price_per_participant,json=pricePerParticipant,proto3" json:"price_per_participant,omitempty"`
	Visibility          SessionVisibility      `protobuf:"varint,8,opt,name=visibility,proto3,enum=session.v1.SessionVisibility" json:"visibility,omitempty"`
	Description         string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CreateSessionRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CreateSessionRequest) GetSportType() string {
	if x != nil {
		return x.SportType
	}
	return ""
}

func (x *CreateSessionRequest) GetSkillLevel() string {
	if x != nil {
		return x.SkillLevel
	}
	return ""
}

func (x *CreateSessionRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *CreateSessionRequest) GetMinParticipants() int32 {
	if x != nil {
		return x.MinParticipants
	}
	return 0
}

func (x *CreateSessionRequest) GetPricePerParticipant() float64 {
	if x != nil {
		return x.PricePerParticipant
	}
	return 0
}

func (x *CreateSessionRequest) GetVisibility() SessionVisibility {
	if x != nil {
		return x.Visibility
	}
	return SessionVisibility_SESSION_VISIBILITY_UNSPECIFIED
}

func (x *CreateSessionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReservationId       string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	HostId              string                 `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	SportType           string                 `protobuf:"bytes,4,opt,name=sport_type,json=sportType,proto3" json:"sport_type,omitempty"`
	SkillLevel          string                 `protobuf:"bytes,5,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"`
	MaxParticipants     int32                  `protobuf:"varint,6,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	MinParticipants     int32                  `protobuf:"varint,7,opt,name=min_participants,json=minParticipants,proto3" json:"min_participants,omitempty"`
	CurrentParticipants int32                  `protobuf:"varint,8,opt,name=current_participants,json=currentParticipants,proto3" json:"current_participants,omitempty"`
	PricePerParticipant float64                `protobuf:"fixed64,9,opt,name=price_per_participant,json=pricePerParticipant,proto3" json:"price_per_participant,omitempty"`
	Visibility          SessionVisibility      `protobuf:"varint,10,opt,name=visibility,proto3,enum=session.v1.SessionVisibility" json:"visibility,omitempty"`
	Status              SessionStatus          `protobuf:"varint,11,opt,name=status,proto3,enum=session.v1.SessionStatus" json:"status,omitempty"`
	Description         string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_api_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *GetSessionResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *GetSessionResponse) GetSportType() string {
	if x != nil {
		return x.SportType
	}
	return ""
}

func (x *GetSessionResponse) GetSkillLevel() string {
	if x != nil {
		return x.SkillLevel
	}
	return ""
}

func (x *GetSessionResponse) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *GetSessionResponse) GetMinParticipants() int32 {
	if x != nil {
		return x.MinParticipants
	}
	return 0
}

func (x *GetSessionResponse) GetCurrentParticipants() int32 {
	if x != nil {
		return x.CurrentParticipants
	}
	return 0
}

func (x *GetSessionResponse) GetPricePerParticipant() float64 {
	if x != nil {
		return x.PricePerParticipant
	}
	return 0
}

func (x *GetSessionResponse) GetVisibility() SessionVisibility {
	if x != nil {
		return x.Visibility
	}
	return SessionVisibility_SESSION_VISIBILITY_UNSPECIFIED
}

func (x *GetSessionResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *GetSessionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSessionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListOpenSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SportType     string                 `protobuf:"bytes,1,opt,name=sport_type,json=sportType,proto3" json:"sport_type,omitempty"`    // Filter by sport (optional)
	SkillLevel    string                 `protobuf:"bytes,2,opt,name=skill_level,json=skillLevel,proto3" json:"skill_level,omitempty"` // Filter by skill level (optional)
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenSessionsRequest) Reset() {
	*x = ListOpenSessionsRequest{}
	mi := &file_api_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenSessionsRequest) ProtoMessage() {}

func (x *ListOpenSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListOpenSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *ListOpenSessionsRequest) GetSportType() string {
	if x != nil {
		return x.SportType
	}
	return ""
}

func (x *ListOpenSessionsRequest) GetSkillLevel() string {
	if x != nil {
		return x.SkillLevel
	}
	return ""
}

func (x *ListOpenSessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOpenSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOpenSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetSessionResponse  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenSessionsResponse) Reset() {
	*x = ListOpenSessionsResponse{}
	mi := &file_api_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenSessionsResponse) ProtoMessage() {}

func (x *ListOpenSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListOpenSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *ListOpenSessionsResponse) GetItems() []*GetSessionResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListOpenSessionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsRequest) Reset() {
	*x = ListUserSessionsRequest{}
	mi := &file_api_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsRequest) ProtoMessage() {}

func (x *ListUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserSessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetSessionResponse  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsResponse) Reset() {
	*x = ListUserSessionsResponse{}
	mi := &file_api_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsResponse) ProtoMessage() {}

func (x *ListUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserSessionsResponse) GetItems() []*GetSessionResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUserSessionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CancelSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Must be host
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSessionRequest) Reset() {
	*x = CancelSessionRequest{}
	mi := &file_api_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSessionRequest) ProtoMessage() {}

func (x *CancelSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSessionRequest.ProtoReflect.Descriptor instead.
func (*CancelSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *CancelSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSessionResponse) Reset() {
	*x = CancelSessionResponse{}
	mi := &file_api_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSessionResponse) ProtoMessage() {}

func (x *CancelSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSessionResponse.ProtoReflect.Descriptor instead.
func (*CancelSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *CancelSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Participant messages
type JoinSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionRequest) Reset() {
	*x = JoinSessionRequest{}
	mi := &file_api_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionRequest) ProtoMessage() {}

func (x *JoinSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionRequest.ProtoReflect.Descriptor instead.
func (*JoinSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *JoinSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinSessionResponse) Reset() {
	*x = JoinSessionResponse{}
	mi := &file_api_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSessionResponse) ProtoMessage() {}

func (x *JoinSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSessionResponse.ProtoReflect.Descriptor instead.
func (*JoinSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *JoinSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinSessionResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type LeaveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionRequest) Reset() {
	*x = LeaveSessionRequest{}
	mi := &file_api_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionRequest) ProtoMessage() {}

func (x *LeaveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionRequest.ProtoReflect.Descriptor instead.
func (*LeaveSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LeaveSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSessionResponse) Reset() {
	*x = LeaveSessionResponse{}
	mi := &file_api_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionResponse) ProtoMessage() {}

func (x *LeaveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionResponse.ProtoReflect.Descriptor instead.
func (*LeaveSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *LeaveSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListSessionParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionParticipantsRequest) Reset() {
	*x = ListSessionParticipantsRequest{}
	mi := &file_api_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionParticipantsRequest) ProtoMessage() {}

func (x *ListSessionParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *ListSessionParticipantsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          ParticipantRole        `protobuf:"varint,3,opt,name=role,proto3,enum=session.v1.ParticipantRole" json:"role,omitempty"`
	Status        ParticipantStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=session.v1.ParticipantStatus" json:"status,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_api_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *Participant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Participant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Participant) GetRole() ParticipantRole {
	if x != nil {
		return x.Role
	}
	return ParticipantRole_PARTICIPANT_ROLE_UNSPECIFIED
}

func (x *Participant) GetStatus() ParticipantStatus {
	if x != nil {
		return x.Status
	}
	return ParticipantStatus_PARTICIPANT_STATUS_UNSPECIFIED
}

func (x *Participant) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

type ListSessionParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionParticipantsResponse) Reset() {
	*x = ListSessionParticipantsResponse{}
	mi := &file_api_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionParticipantsResponse) ProtoMessage() {}

func (x *ListSessionParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_session_proto_rawDescGZIP(), []int{16}
}

func (x *ListSessionParticipantsResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

var File_api_v1_session_proto protoreflect.FileDescriptor

const file_api_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/session.proto\x12\n" +
	"session.v1\"\x81\x03\n" +
	"\x14CreateSessionRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"sport_type\x18\x03 \x01(\tR\tsportType\x12\x1f\n" +
	"\vskill_level\x18\x04 \x01(\tR\n" +
	"skillLevel\x12)\n" +
	"\x10max_participants\x18\x05 \x01(\x05R\x0fmaxParticipants\x12)\n" +
	"\x10min_participants\x18\x06 \x01(\x05R\x0fminParticipants\x122\n" +
	"\x15price_per_participant\x18\a \x01(\x01R\x13pricePerParticipant\x12=\n" +
	"\n" +
	"visibility\x18\b \x01(\x0e2\x1d.session.v1.SessionVisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb3\x04\n" +
	"\x12GetSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x17\n" +
	"\ahost_id\x18\x03 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"sport_type\x18\x04 \x01(\tR\tsportType\x12\x1f\n" +
	"\vskill_level\x18\x05 \x01(\tR\n" +
	"skillLevel\x12)\n" +
	"\x10max_participants\x18\x06 \x01(\x05R\x0fmaxParticipants\x12)\n" +
	"\x10min_participants\x18\a \x01(\x05R\x0fminParticipants\x121\n" +
	"\x14current_participants\x18\b \x01(\x05R\x13currentParticipants\x122\n" +
	"\x15price_per_participant\x18\t \x01(\x01R\x13pricePerParticipant\x12=\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\x0e2\x1d.session.v1.SessionVisibilityR\n" +
	"visibility\x121\n" +
	"\x06status\x18\v \x01(\x0e2\x19.session.v1.SessionStatusR\x06status\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\x8a\x01\n" +
	"\x17ListOpenSessionsRequest\x12\x1d\n" +
	"\n" +
	"sport_type\x18\x01 \x01(\tR\tsportType\x12\x1f\n" +
	"\vskill_level\x18\x02 \x01(\tR\n" +
	"skillLevel\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"q\n" +
	"\x18ListOpenSessionsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.session.v1.GetSessionResponseR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"c\n" +
	"\x17ListUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"q\n" +
	"\x18ListUserSessionsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.session.v1.GetSessionResponseR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"N\n" +
	"\x14CancelSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15CancelSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x12JoinSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"V\n" +
	"\x13JoinSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"M\n" +
	"\x13LeaveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x14LeaveSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x1eListSessionParticipantsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xbb\x01\n" +
	"\vParticipant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12/\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1b.session.v1.ParticipantRoleR\x04role\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.session.v1.ParticipantStatusR\x06status\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\tR\bjoinedAt\"^\n" +
	"\x1fListSessionParticipantsResponse\x12;\n" +
	"\fparticipants\x18\x01 \x03(\v2\x17.session.v1.ParticipantR\fparticipants*\xbd\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SESSION_STATUS_OPEN\x10\x01\x12\x17\n" +
	"\x13SESSION_STATUS_FULL\x10\x02\x12\x1e\n" +
	"\x1aSESSION_STATUS_IN_PROGRESS\x10\x03\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x04\x12\x1c\n" +
	"\x18SESSION_STATUS_CANCELLED\x10\x05*v\n" +
	"\x11SessionVisibility\x12\"\n" +
	"\x1eSESSION_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SESSION_VISIBILITY_PUBLIC\x10\x01\x12\x1e\n" +
	"\x1aSESSION_VISIBILITY_PRIVATE\x10\x02*k\n" +
	"\x0fParticipantRole\x12 \n" +
	"\x1cPARTICIPANT_ROLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PARTICIPANT_ROLE_HOST\x10\x01\x12\x1b\n" +
	"\x17PARTICIPANT_ROLE_PLAYER\x10\x02*\x93\x01\n" +
	"\x11ParticipantStatus\x12\"\n" +
	"\x1ePARTICIPANT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PARTICIPANT_STATUS_JOINED\x10\x01\x12\x1b\n" +
	"\x17PARTICIPANT_STATUS_LEFT\x10\x02\x12\x1e\n" +
	"\x1aPARTICIPANT_STATUS_REMOVED\x10\x032\xde\x05\n" +
	"\x0eSessionService\x12T\n" +
	"\rCreateSession\x12 .session.v1.CreateSessionRequest\x1a!.session.v1.CreateSessionResponse\x12K\n" +
	"\n" +
	"GetSession\x12\x1d.session.v1.GetSessionRequest\x1a\x1e.session.v1.GetSessionResponse\x12]\n" +
	"\x10ListOpenSessions\x12#.session.v1.ListOpenSessionsRequest\x1a$.session.v1.ListOpenSessionsResponse\x12]\n" +
	"\x10ListUserSessions\x12#.session.v1.ListUserSessionsRequest\x1a$.session.v1.ListUserSessionsResponse\x12T\n" +
	"\rCancelSession\x12 .session.v1.CancelSessionRequest\x1a!.session.v1.CancelSessionResponse\x12N\n" +
	"\vJoinSession\x12\x1e.session.v1.JoinSessionRequest\x1a\x1f.session.v1.JoinSessionResponse\x12Q\n" +
	"\fLeaveSession\x12\x1f.session.v1.LeaveSessionRequest\x1a .session.v1.LeaveSessionResponse\x12r\n" +
	"\x17ListSessionParticipants\x12*.session.v1.ListSessionParticipantsRequest\x1a+.session.v1.ListSessionParticipantsResponseB1Z/github.com/diploma/session-svc/api/v1;sessionv1b\x06proto3"

var (
	file_api_v1_session_proto_rawDescOnce sync.Once
	file_api_v1_session_proto_rawDescData []byte
)

func file_api_v1_session_proto_rawDescGZIP() []byte {
	file_api_v1_session_proto_rawDescOnce.Do(func() {
		file_api_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_session_proto_rawDesc), len(file_api_v1_session_proto_rawDesc)))
	})
	return file_api_v1_session_proto_rawDescData
}

var file_api_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_v1_session_proto_goTypes = []any{
	(SessionStatus)(0),                      // 0: session.v1.SessionStatus
	(SessionVisibility)(0),                  // 1: session.v1.SessionVisibility
	(ParticipantRole)(0),                    // 2: session.v1.ParticipantRole
	(ParticipantStatus)(0),                  // 3: session.v1.ParticipantStatus
	(*CreateSessionRequest)(nil),            // 4: session.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),           // 5: session.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),               // 6: session.v1.GetSessionRequest
	(*GetSessionResponse)(nil),              // 7: session.v1.GetSessionResponse
	(*ListOpenSessionsRequest)(nil),         // 8: session.v1.ListOpenSessionsRequest
	(*ListOpenSessionsResponse)(nil),        // 9: session.v1.ListOpenSessionsResponse
	(*ListUserSessionsRequest)(nil),         // 10: session.v1.ListUserSessionsRequest
	(*ListUserSessionsResponse)(nil),        // 11: session.v1.ListUserSessionsResponse
	(*CancelSessionRequest)(nil),            // 12: session.v1.CancelSessionRequest
	(*CancelSessionResponse)(nil),           // 13: session.v1.CancelSessionResponse
	(*JoinSessionRequest)(nil),              // 14: session.v1.JoinSessionRequest
	(*JoinSessionResponse)(nil),             // 15: session.v1.JoinSessionResponse
	(*LeaveSessionRequest)(nil),             // 16: session.v1.LeaveSessionRequest
	(*LeaveSessionResponse)(nil),            // 17: session.v1.LeaveSessionResponse
	(*ListSessionParticipantsRequest)(nil),  // 18: session.v1.ListSessionParticipantsRequest
	(*Participant)(nil),                     // 19: session.v1.Participant
	(*ListSessionParticipantsResponse)(nil), // 20: session.v1.ListSessionParticipantsResponse
}
var file_api_v1_session_proto_depIdxs = []int32{
	1,  // 0: session.v1.CreateSessionRequest.visibility:type_name -> session.v1.SessionVisibility
	1,  // 1: session.v1.GetSessionResponse.visibility:type_name -> session.v1.SessionVisibility
	0,  // 2: session.v1.GetSessionResponse.status:type_name -> session.v1.SessionStatus
	7,  // 3: session.v1.ListOpenSessionsResponse.items:type_name -> session.v1.GetSessionResponse
	7,  // 4: session.v1.ListUserSessionsResponse.items:type_name -> session.v1.GetSessionResponse
	2,  // 5: session.v1.Participant.role:type_name -> session.v1.ParticipantRole
	3,  // 6: session.v1.Participant.status:type_name -> session.v1.ParticipantStatus
	19, // 7: session.v1.ListSessionParticipantsResponse.participants:type_name -> session.v1.Participant
	4,  // 8: session.v1.SessionService.CreateSession:input_type -> session.v1.CreateSessionRequest
	6,  // 9: session.v1.SessionService.GetSession:input_type -> session.v1.GetSessionRequest
	8,  // 10: session.v1.SessionService.ListOpenSessions:input_type -> session.v1.ListOpenSessionsRequest
	10, // 11: session.v1.SessionService.ListUserSessions:input_type -> session.v1.ListUserSessionsRequest
	12, // 12: session.v1.SessionService.CancelSession:input_type -> session.v1.CancelSessionRequest
	14, // 13: session.v1.SessionService.JoinSession:input_type -> session.v1.JoinSessionRequest
	16, // 14: session.v1.SessionService.LeaveSession:input_type -> session.v1.LeaveSessionRequest
	18, // 15: session.v1.SessionService.ListSessionParticipants:input_type -> session.v1.ListSessionParticipantsRequest
	5,  // 16: session.v1.SessionService.CreateSession:output_type -> session.v1.CreateSessionResponse
	7,  // 17: session.v1.SessionService.GetSession:output_type -> session.v1.GetSessionResponse
	9,  // 18: session.v1.SessionService.ListOpenSessions:output_type -> session.v1.ListOpenSessionsResponse
	11, // 19: session.v1.SessionService.ListUserSessions:output_type -> session.v1.ListUserSessionsResponse
	13, // 20: session.v1.SessionService.CancelSession:output_type -> session.v1.CancelSessionResponse
	15, // 21: session.v1.SessionService.JoinSession:output_type -> session.v1.JoinSessionResponse
	17, // 22: session.v1.SessionService.LeaveSession:output_type -> session.v1.LeaveSessionResponse
	20, // 23: session.v1.SessionService.ListSessionParticipants:output_type -> session.v1.ListSessionParticipantsResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1_session_proto_init() }
func file_api_v1_session_proto_init() {
	if File_api_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_session_proto_rawDesc), len(file_api_v1_session_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_session_proto_goTypes,
		DependencyIndexes: file_api_v1_session_proto_depIdxs,
		EnumInfos:         file_api_v1_session_proto_enumTypes,
		MessageInfos:      file_api_v1_session_proto_msgTypes,
	}.Build()
	File_api_v1_session_proto = out.File
	file_api_v1_session_proto_goTypes = nil
	file_api_v1_session_proto_depIdxs = nil
}
